# Generated by Django 4.1.2 on 2022-10-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avanzo',
            name='empresas_vinculadas',
        ),
        migrations.AddField(
            model_name='avanzo',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
