# Generated by Django 4.1.2 on 2022-10-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
